#
# This test file has been generated by kwb.test::create_test_files()
# launched by user micha on 2020-06-26 00:11:51.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_tidy_traveltimes() works", {

  expect_error(
    kwb.heatsine:::get_tidy_traveltimes()
    # Argument "traveltimes" fehlt (ohne Standardwert)
  )

})

