#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2020-10-09 13:39:47.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("add_phi() works", {

  expect_error(
    kwb.heatsine:::add_phi()
    # Argument "df" fehlt (ohne Standardwert)
  )

})

